//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Cod3rsGrowth
	/// Data Source    : INVENT003
	/// Server Version : 16.00.1000
	/// </summary>
	public partial class Cod3rsGrowthDB : LinqToDB.Data.DataConnection
	{
		public ITable<Peca>        Pecas       { get { return this.GetTable<Peca>(); } }
		public ITable<VersionInfo> VersionInfo { get { return this.GetTable<VersionInfo>(); } }

		public Cod3rsGrowthDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public Cod3rsGrowthDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public Cod3rsGrowthDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public Cod3rsGrowthDB(DataOptions<Cod3rsGrowthDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Pecas")]
	public partial class Peca
	{
		[PrimaryKey, Identity] public int      Id               { get; set; } // int
		[Column,     NotNull ] public string   Categoria        { get; set; } // nvarchar(255)
		[Column,     NotNull ] public string   Nome             { get; set; } // nvarchar(255)
		[Column,     NotNull ] public string   Descricao        { get; set; } // nvarchar(255)
		[Column,     NotNull ] public int      Estoque          { get; set; } // int
		[Column,     NotNull ] public DateTime DataDeFabricacao { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="VersionInfo")]
	public partial class VersionInfo
	{
		[Column, NotNull    ] public long      Version     { get; set; } // bigint
		[Column,    Nullable] public DateTime? AppliedOn   { get; set; } // datetime
		[Column,    Nullable] public string    Description { get; set; } // nvarchar(1024)
	}

	public static partial class TableExtensions
	{
		public static Peca Find(this ITable<Peca> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
